apiVersion: batch/v1
kind: CronJob
metadata:
  name: ha-dashboard-screenshot
spec:
  schedule: "*/6 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
          containers:
          - name: screenshot
            image: ghcr.io/jeboehm/ha-dashboard-screenshot:main
            securityContext:
              allowPrivilegeEscalation: false
              runAsUser: 1000
              runAsGroup: 1000
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: "200m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
            envFrom:
            - secretRef:
                name: ha-dashboard-screenshot-secret
            volumeMounts:
            - name: screenshot-volume
              mountPath: /app/output
            args: []
          volumes:
          - name: screenshot-volume
            persistentVolumeClaim:
              claimName: ha-dashboard-screenshot-pvc
