apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-dashboard-screenshot-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
